version: "3"

services: 
  db:
    image: mysql:5.5 
    ports: 
      - "8082:3306"
    volumes: 
      - db_data:/var/lib/mysql
      - .:/TodoList
    environment: 
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: TodoList
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes: 
      - .:/TodoList
    ports: 
      - "8000:80"
    depends_on: 
      - db
    stdin_open: true
    tty: true
volumes:
  db_data: